FROM gradle:8.2-jdk17-alpine

WORKDIR /keycloak-initializer

COPY build.gradle .
COPY settings.gradle .

COPY src/ src/

RUN gradle build

RUN mv build/libs/keycloak-initializer-1.0.jar keycloak-initializer.jar

CMD ["java", "-jar", "keycloak-initializer.jar"]

