# Required volumes:
#     - "./keycloak-initializer:/keycloak-initializer"
#     - "./.cache/keycloak-initializer/.gradle:/keycloak-initializer/.gradle"
#     - "./.cache/keycloak-initializer/build:/keycloak-initializer/build"

FROM gradle:8.2-jdk17-alpine

WORKDIR /keycloak-initializer

CMD ["gradle", "run"]
