# Required volumes:
#     - "./keycloak-initializer:/keycloak-initializer"
#     - "./.cache/keycloak-initializer/.gradle:/keycloak-initializer/.gradle"
#     - "./.cache/keycloak-initializer/build:/keycloak-initializer/build"

FROM alpine:3.19.1

RUN apk update --no-cache && apk add --no-cache gradle

WORKDIR /keycloak-initializer

CMD ["gradle", "run"]
