version: "2.1"

services:
    corn-postgres:
        container_name: corn-postgres
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=none
            - POSTGRES_DB=corn
        ports:
            - "5000:5432"
    corn-backend:
        container_name: corn-backend
        image: corn-backend
        depends_on:
            - corn-postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=none
            - POSTGRES_DB=corn
            - SPRING_DATASOURCE_URL=jdbc:postgresql://corn-postgres:5432/corn
            - FRONTEND_URL=corn-frontend
        build:
            context: corn-backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    corn-frontend:
        container_name: corn-frontend
        image: corn-frontend
        depends_on:
            - corn-backend
        build:
            context: corn-frontend
            dockerfile: Dockerfile
        ports:
            - "4200:80"

    corn-keycloak-initializer:
        container_name: corn-keycloak-initializer
        image: corn-keycloak-initializer
        build:
            context: keycloak-initializer
            dockerfile: Dockerfile
        depends_on:
            corn-keycloak:
                condition: service_healthy
        environment:
            - KCCFG_OVERRIDE_EXISTING=true
            - KC_SERVER_URL=http://corn-keycloak:8080
    corn-keycloak:
        container_name: corn-keycloak
        image: quay.io/keycloak/keycloak:20.0.1
        depends_on:
            corn-keycloak-postgres:
                condition: service_healthy
        environment:
            - KC_DB=postgres
            - KC_DB_URL=jdbc:postgresql://corn-keycloak-postgres:5432/keycloak
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB_USERNAME=keycloak
            - KC_DB_PASSWORD=none
        command: start-dev
        ports:
            - '8081:8080'
        healthcheck:
            test: "curl -f http://localhost:8080/admin || exit 1"
    corn-keycloak-postgres:
        container_name: corn-keycloak-postgres
        image: postgres:alpine
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=none
        ports:
            - "5001:5432"
        healthcheck:
            test: "pg_isready -U keycloak"
