server:
    port: 8080

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/realms/Corn
                    jwk-set-uri: http://corn-keycloak:8080/realms/Corn/protocol/openid-connect/certs
app:
    jwt:
        issuer-uri: http://corn-keycloak:8080/realms/Corn
        resource-client-ids: Corn