server:
    port: 8081

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

                format_sql: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${app.jwt.public-issuer-uri}
                    jwk-set-uri: ${app.jwt.local-issuer-uri}/protocol/openid-connect/certs
app:
    jwt:
        #id klienta, z którym jest skojarzona ta aplikacja
        resource-client-ids: Corn
        #lokalne URI emitenta tokenów
        local-issuer-uri: http://corn-keycloak:8080/realms/Corn
        #publiczne URI emitenta tokenów
        public-issuer-uri: http://localhost:8081/realms/Corn