server:
    port: 8080

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
