FROM alpine:3.19.1 AS build

WORKDIR /corn

RUN apk update --no-cache && apk add --no-cache nodejs npm

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:corn:prod

FROM alpine:3.19.1

WORKDIR /corn-theme

COPY --from=build /corn/styles ./styles

COPY --from=build /corn/themes ./themes
