# Required volumes:
#     - "./keycloak-theme:/keycloak-theme"
#     - "./.cache/keycloak-theme/node_modules:/keycloak-theme/node_modules"

FROM node:18.15-alpine as node

WORKDIR /keycloak-theme

ENTRYPOINT ["/bin/sh", "-c", "npm install;npm run build:corn:dev"]
