FROM alpine:3.19.1 AS build

WORKDIR /keycloak-theme

RUN apk update --no-cache && apk add --no-cache nodejs npm

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:corn:prod


FROM alpine:3.19.1

RUN apk update --no-cache && apk add --no-cache zip

COPY --from=build /keycloak-theme/themes ./theme
COPY --from=build /keycloak-theme/META-INF ./META-INF
RUN zip -r corn-theme.jar theme META-INF

CMD ["/bin/sh", "-c", "cp /corn-theme.jar /artifacts"]
