FROM alpine:3.19.1 AS build

RUN apk update --no-cache && apk upgrade --no-cache && apk add --no-cache gradle

WORKDIR /home/corn

COPY build.gradle .

COPY settings.gradle .

COPY src/ src/

RUN gradle build -x test

RUN mv build/libs/corn-backend-0.0.1-SNAPSHOT.jar corn.jar

FROM alpine:3.19.1

RUN apk update --no-cache && apk upgrade --no-cache && apk add --no-cache openjdk17-jre

WORKDIR /corn

COPY --from=build /home/corn/corn.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "corn.jar"]
