# Required volumes:
#    - "./corn-backend:/home/corn"
#    - "./.cache/corn-backend/.gradle:/home/corn/.gradle"
#    - "./.cache/corn-backend/build:/home/corn/build"

FROM gradle:8.2-jdk17-alpine

WORKDIR /home/corn

EXPOSE 8080
EXPOSE 5005

CMD ["gradle", "bootRun"]
