# Required volumes:
#    - "./corn-backend:/home/corn"
#    - "./.cache/corn-backend/.gradle:/home/corn/.gradle"
#    - "./.cache/corn-backend/build:/home/corn/build"

FROM alpine:3.19.1

RUN apk update --no-cache && apk add --no-cache gradle

WORKDIR /home/corn

EXPOSE 8080

EXPOSE 5005

CMD ["gradle", "bootRun"]
