# Required volumes:
#     - "./corn-frontend:/corn-frontend"
#     - "./.cache/corn-frontend/node_modules:/corn-frontend/node_modules"
#     - "./.cache/corn-frontend/dist:/corn-frontend/dist"

FROM node:18.15-alpine as node

WORKDIR /corn-frontend

ENTRYPOINT ["/bin/sh", "-c", "npm install;npm run start-dev"]

EXPOSE 80