# Required volumes:
#     - "./corn-frontend:/corn-frontend"
#     - "./.cache/corn-frontend/node_modules:/corn-frontend/node_modules"
#     - "./.cache/corn-frontend/dist:/corn-frontend/dist"

FROM alpine:3.19.1

RUN apk update --no-cache && apk upgrade --no-cache && apk add --no-cache nodejs npm curl

WORKDIR /corn-frontend

ENTRYPOINT ["/bin/sh", "-c", "npm install;npm run start-dev"]

EXPOSE 80